title: Ash Caire
baseURL: https://blog.caire.io/
languageCode: en-au
theme:
  - hugo-notice
  - stack

permalinks:
  post: /p/:slug/
  page: /:slug/

params:
  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0
  mainSections:
  - post
  comments:
     enabled: true
     provider: utterances

     utterances:
       enabled: true
       repo: acaire/blog-comments
       issueTerm: pathname
       label: foobar
  sidebar:
    emoji: 😂
    subtitle: Passionate about all things automation, particularly state and discovery.
    avatar:
      enabled: true
      local: false
      src: https://avatars.githubusercontent.com/u/797119?v=4

  widgets:
    enabled:
    - search
    - archives
    - tag-cloud

menu:
  social:
  - identifier: github
    name: GitHub
    url: https://github.com/acaire
    params:
      icon: brand-github
  - identifier: twitter
    name: Twitter
    url: https://twitter.com/ashcaire
    params:
      icon: brand-twitter
  - identifier: linkedin
    name: LinkedIn
    url: https://www.linkedin.com/in/ashcaire/
    params:
      icon: brand-linkedin


